# DecodeLabs Data Science Internship Project

## Product Sales Region Dataset Analysis

**Intern Name:** Priyanka Makwana  
**Domain:** Data Science  
**Internship:** DecodeLabs  
**Dataset:** Product-Sales-Region.xlsx

---

# TASK 3: Exploratory Data Analysis (EDA)

### Objective

The objective of this task is to analyze the dataset, identify trends, discover patterns, detect outliers, and generate meaningful business insights.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings

warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (10, 5)

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
df = pd.read_excel('Product-Sales-Region.xlsx')

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 1500
Columns: 19

## Step 3.1 Basic Statistical Analysis

Descriptive statistics are calculated to understand the distribution, central tendency, and variability of numerical features.

In [4]:
df['Date'] = pd.to_datetime(df['Date'])
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df['DeliveryDate'] = pd.to_datetime(df['DeliveryDate'])

In [5]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['MonthName'] = df['Date'].dt.strftime('%b')
df['Quarter'] = df['Date'].dt.quarter

df['DeliveryDays'] = (
    df['DeliveryDate'] - df['OrderDate']
).dt.days

df[['Year','Month','MonthName','Quarter','DeliveryDays']].head()

   Year  Month MonthName  Quarter  DeliveryDays
0  2023      2       Feb        1             4
1  2024     12       Dec        4             9
2  2023      5       May        2             9
3  2025      2       Feb        1             4
4  2023      6       Jun        2             3

In [6]:
print("Basic Statistical Summary")

df[['Quantity', 'UnitPrice', 'Discount',
    'TotalPrice', 'ShippingCost',
    'DeliveryDays']].describe().round(2)

Basic Statistical Summary

       Quantity  UnitPrice  Discount  TotalPrice  ShippingCost  DeliveryDays
count   1500.00    1500.00   1500.00     1500.00       1500.00       1500.00
mean      10.41     298.83      0.07     2919.99         27.51          6.04
std        5.74     169.10      0.06     2522.79         13.09          2.54
min        1.00       5.52      0.00        6.97          5.01          2.00
25%        5.00     151.02      0.00      867.14         16.70          4.00
50%       11.00     294.74      0.05     2174.72         27.10          6.00
75%       15.00     446.70      0.10     4414.72         38.64          8.00
max       20.00     599.72      0.15    11077.00         49.98         10.00

## Step 3.2 Sales Revenue Analysis by Region

This analysis helps identify which region contributes the highest revenue.

In [7]:
region_sales = df.groupby('Region')['TotalPrice'].sum().sort_values(ascending=False)

print("Total Sales Revenue by Region")
print(region_sales.round(2))

Total Sales Revenue by Region
Region
North      967957.98
East       883633.72
West       853478.86
Central    847153.68
South      827768.19
Name: TotalPrice, dtype: float64

## Step 3.3 Product Performance Analysis

This analysis identifies the products generating the highest revenue.

In [8]:
product_sales = df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False)

print("Total Sales Revenue by Product")
print(product_sales.round(2))

Total Sales Revenue by Product
Product
Tablet     684539.39
Laptop     684417.24
Printer    684387.42
Monitor    651629.39
Chair      622589.48
Desk       555266.66
Phone      497162.85
Name: TotalPrice, dtype: float64

## Step 3.4 Monthly Sales Trend Analysis

Monthly sales trends are analyzed to identify seasonal patterns and revenue fluctuations.

In [9]:
monthly_sales = df.groupby(
    ['Year', 'Month']
)['TotalPrice'].sum().reset_index()

monthly_sales = monthly_sales.sort_values(
    ['Year', 'Month']
)

monthly_sales.tail(12)

    Year  Month   TotalPrice
18  2024      7  140155.7075
19  2024      8  129927.5060
20  2024      9  130502.6035
21  2024     10  178167.1965
22  2024     11  138174.2850
23  2024     12  143039.6205
24  2025      1  171098.0930
25  2025      2  138184.6330
26  2025      3  183193.7690
27  2025      4  128675.0145
28  2025      5  152349.6110
29  2025      6  136666.5515

## Step 3.5 Return Rate Analysis

Return rates are analyzed to identify products with higher customer return behavior.

In [10]:
return_rate = df.groupby(
    'Product'
)['Returned'].mean() * 100

print(return_rate.round(2).sort_values(
    ascending=False
))

Product
Chair      28.23
Laptop     27.43
Monitor    26.42
Tablet     24.17
Phone      23.08
Printer    22.27
Desk       21.74
Name: Returned, dtype: float64

## Step 3.6 Customer Type Analysis

Revenue contribution from Retail and Wholesale customers is analyzed.

In [11]:
df.groupby(
    'CustomerType'
)['TotalPrice'].agg(
    ['sum', 'mean', 'count']
).round(2)

                     sum     mean  count
CustomerType
Retail        2195525.59  2950.98    744
Wholesale     2184466.84  2889.51    756

## Step 3.7 Top Salesperson Analysis

The highest-performing salespersons are identified based on revenue generation.

In [12]:
top_sales = df.groupby(
    'Salesperson'
)['TotalPrice'].sum().sort_values(
    ascending=False
).head(5)

print(top_sales.round(2))

Salesperson
Bob       796780.52
Alice     786165.84
Frank     714641.52
Carlos    707166.72
Eva       698669.58
Name: TotalPrice, dtype: float64

## Step 3.8 Correlation Analysis

Correlation analysis helps understand relationships between numerical variables.

In [13]:
corr = df[['Quantity',
           'UnitPrice',
           'Discount',
           'TotalPrice',
           'ShippingCost',
           'DeliveryDays']].corr()

corr.round(2)

,Quantity,UnitPrice,Discount,TotalPrice,ShippingCost,DeliveryDays
Quantity,1.00,0.04,0.02,0.67,-0.02,-0.01
UnitPrice,0.04,1.00,0.01,0.68,0.00,-0.01
Discount,0.02,0.01,1.00,-0.06,-0.03,-0.01
TotalPrice,0.67,0.68,-0.06,1.00,-0.01,-0.02
ShippingCost,-0.02,0.00,-0.03,-0.01,1.00,-0.03
DeliveryDays,-0.01,-0.01,-0.01,-0.02,-0.03,1.00

## Step 3.9 Outlier Detection

The Interquartile Range (IQR) method is used to identify unusual sales transactions.

In [14]:
Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - (1.5 * IQR)
upper = Q3 + (1.5 * IQR)

outliers = df[
    (df['TotalPrice'] < lower) |
    (df['TotalPrice'] > upper)
]

print("Q1 =", round(Q1, 2))
print("Q3 =", round(Q3, 2))
print("IQR =", round(IQR, 2))
print("Lower Bound =", round(lower, 2))
print("Upper Bound =", round(upper, 2))
print("Number of Outliers =", len(outliers))

Q1 = 867.14
Q3 = 4414.72
IQR = 3547.59
Lower Bound = -4454.24
Upper Bound = 9736.1
Number of Outliers = 17

## Task 3 Conclusion

### Key Findings

- Revenue distribution was analyzed across regions and products.
- Monthly sales trends were identified.
- Customer return behavior was examined.
- Retail and Wholesale customer contributions were compared.
- Correlation analysis revealed relationships between important variables.
- High-value outlier transactions were detected successfully.

### Outcome

The exploratory data analysis phase has been completed successfully. The dataset insights obtained in this task will support effective visualization and predictive modeling in the next stages.